name: Test Helm Chart

on:
  push:
    paths:
      - "charts/**"
  pull_request:
    paths:
      - "charts/**"

jobs:
  helm-lint-and-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Lint the chart
        run: helm lint charts/mosquitto

      - name: Template with default values
        run: helm template test charts/mosquitto

      - name: Template with test-values
        run: helm template test charts/mosquitto -f charts/mosquitto/test-values.yaml
